# Improved Configuration - Wider ranges for better exploration
experiment:
  name: "euclidean"
  output_csv: "optimization_results.csv"

  constants_file:
    path: "/Users/apoorv.dixit/Desktop/decision-engine/sr_cost_routing_constants.json"
    section: "sr_cost_routing_constants"

trials:
  startup: 3 # Increased from 10 for better initial exploration
  total: 10 # Increased from 25 for more trials
  parallel_jobs: 2

objectives:
  success_rate: "maximize"
  missed_savings: "minimize"

  aggregation:
    success_rate: "mean"
    missed_savings: "mean"

baseline:
  parameters:
    sr_threshold: 0.85
    spread_threshold: 0.02
    alpha: 3.0
    beta: 1.0

  results:
    - dataset: "scene-1"
      success_rate: 98.10666667
      missed_savings: 1.67

    - dataset: "scene-2"
      success_rate: 96.42666667
      missed_savings: 1.67

    - dataset: "scene-3"
      success_rate: 94.45333333
      missed_savings: 1.0

    - dataset: "scene-4"
      success_rate: 93.33333333
      missed_savings: 0.0

    - dataset: "scene-5"
      success_rate: 87.72
      missed_savings: 0.0

parameters:
  # WIDENED RANGES FOR BETTER EXPLORATION

  - name: "sr_threshold"
    type: "float"
    precision: 2
    range:
      low: 0.70 # Widened from 0.85 - allows exploring lower values
      high: 0.98 # Slightly below 1.0 to avoid edge cases

  - name: "spread_threshold"
    type: "float"
    precision: 3 # Increased precision for this parameter
    range:
      low: 0.005 # Widened from 0.01 - explore smaller spreads
      high: 0.25 # Widened from 0.2

  - name: "alpha"
    type: "float"
    precision: 2
    range:
      low: 0.1
      high: 5.0 # Widened from 4.0
    log_scale: true

  - name: "beta"
    type: "float"
    precision: 2
    range:
      low: 0.1
      high: 5.0 # Widened from 4.0
    log_scale: true # ADDED log_scale since it spans wide range
