# Configuration optimizing only the success_rate_delta parameter
experiment:
  name: "delta_based"
  output_csv: "success_rate_delta_results.csv"

  constants_file:
    path: "/Users/apoorv.dixit/Desktop/decision-engine/super_router_constants.json"
    section: "sr_cost_routing_constants"

trials:
  startup: 5 # Increased startup trials for better exploration
  total: 15 # Increased total trials for more comprehensive optimization
  parallel_jobs: 2

objectives:
  success_rate: "maximize"
  missed_savings: "minimize"

  aggregation:
    success_rate: "mean"
    missed_savings: "mean"

baseline:
  parameters:
    success_rate_delta: 0.01

parameters:
  # Only success_rate_delta parameter with focused range for better optimization
  - name: "success_rate_delta"
    type: "float"
    precision: 2
    range:
      low: 0.01
      high: 0.20
