# Configuration optimizing success_rate_delta using threshold-based business logic
experiment:
  name: "delta_based"
  output_csv: "success_rate_delta_results.csv"

  constants_file:
    path: "/Users/apoorv.dixit/Desktop/decision-engine/super_router_constants.json"
    section: "sr_cost_routing_constants"

trials:
  startup: 3
  total: 10
  parallel_jobs: 2

objectives:
  success_rate: "maximize"
  missed_savings: "minimize"
  
  # Threshold-based decision logic
  decision_logic:
    type: "threshold"
    success_rate_threshold_percent: 1.0
    baseline_delta: 0.0

  aggregation:
    success_rate: "mean"
    missed_savings: "mean"

baseline:
  parameters:
    success_rate_delta: 0.0  # Always AUTH baseline

parameters:
  - name: "success_rate_delta"
    type: "float"
    precision: 2
    range:
      low: 0.01
      high: 0.15
