# Configuration file for the Decision Engine Testing Framework.
#
# SCENARIO: Multiple Connectors with Different Success Rates
# CASE:     No connector supports debit routing.
#
# This file defines an initial state where multiple processors are active
# with varying success rates, but none have the debit routing capability enabled.

# Global settings for this simulation run.
simulation:
  num_transactions: 2500

# Defines the data model for the entire simulation.
schema:
  transaction_fields:
    - name: "paymentId"
    - name: "amount"
      generator: "random_number"
      params:
        min: 5
        max: 1000
        decimals: 2

    - name: "payment_method_type"
      generator: "random_choice"
      params:
        primary_values: ["CARD", "WALLET"]
        primary_weights: [1.0, 0.0] 

    - generator: "conditional_generator"
      on_field: "payment_method_type"
      conditions:
        "CARD":
          - name: "payment_method"
            generator: "random_choice"
            params:
              primary_values: ["VISA", "MASTERCARD"]
              primary_weights: [0.5, 0.5]

              # The combination logic is defined but commented out for this scenario.
              combinations: [["VISA", "ACCEL","STAR"], ["MASTERCARD", "ACCEL","STAR"]]
              combination_weights: [0.5, 0.5]
              distribution_weights: [0.5, 0.5]

        # "WALLET":
        #   - name: "payment_method"
        #     generator: "random_choice"
        #     params:
        #       primary_values: ["PayPal", "Venmo"]
        #       primary_weights: [0.6, 0.4]

# The list of processors and their default states, which defines our scenario.
processors:
  - name: "Stripe"
    defaults:
      success_rate: 0.98
      supported_networks: ["VISA", "MASTERCARD"]
  - name: "Adyen"
    defaults:
      success_rate: 0.90
      supported_networks: ["VISA", "MASTERCARD","ACCEL","STAR"]

  - name: "Checkout"
    defaults:
      success_rate: 0.82
      supported_networks: ["VISA", "MASTERCARD","ACCEL","STAR"]

# This is empty because the default state already matches the scenario we want to test.
event_schedule: []
