# Configuration file for the Decision Engine Testing Framework.
#
# SCENARIO: Multiple Connectors with Different Success Rates
# CASE:     No connector supports debit routing.
#
# This file defines an initial state where multiple processors are active
# with varying success rates, but none have the debit routing capability enabled.

# Global settings for this simulation run.
simulation:
  num_transactions: 100
  output_csv_path: "./scene-1/transactions.csv"

# Defines the data model for the entire simulation.
schema:
  transaction_fields:
    - name: "amount"
      generator: "random_number"
      params:
        min: 5
        max: 1000
        decimals: 2

    - name: "payment_method_type"
      generator: "random_choice"
      params:
        primary_values: ["CARD", "WALLET"]
        primary_weights: [8.0, 2.0] # 90% CARD, 10% WALLET

    - generator: "conditional_generator"
      on_field: "payment_method_type"
      conditions:
        "CARD":
          - name: "payment_method"
            generator: "random_choice"
            params:
              primary_values: ["Visa", "Mastercard"]
              primary_weights: [0.7, 0.3]

              # The combination logic is defined but commented out for this scenario.
              combinations: [["Visa", "Interlink"], ["Mastercard", "Maestro"]]
              combination_weights: [0.9, 0.1]
              distribution_weights: [0.8, 0.2]

        "WALLET":
          - name: "payment_method"
            generator: "random_choice"
            params:
              primary_values: ["PayPal", "Venmo"]
              primary_weights: [0.6, 0.4]

# The list of processors and their default states, which defines our scenario.
processors:
  - name: "Stripe"
    defaults:
      success_rate: 0.98
  - name: "Adyen"
    defaults:
      success_rate: 0.0
  - name: "PayPal"
    defaults:
      success_rate: 0.94

# This is empty because the default state already matches the scenario we want to test.
event_schedule: []
